### ISSUE TITLE
How

### ISSUE THREAD

**Issue by roflinger** [TheHackLife/TPLink-hs100-PHP-REST-API#1]
Ok i don´t get it:

how do i make it running?  tried 3 hours now

**Comment by TheHackLife** [comment]
Hi sir, 
Are you registered your plugs in the "Kasa" app ? What error are you getting?

**Comment by roflinger** [comment]
hi, i do not even know what to start it with - yes i am registered. i uploaded the php to a php server but a blank website appears

**Comment by TheHackLife** [comment]
Your error.log is empty yoo ? 
Try print myTerminal() and returnToken() and check if the login is working properly
